### ISSUE TITLE
Witch twcmanager fork

### ISSUE THREAD

**Issue by surfarn** [jherby2k/twcmanager_ha#1]
Hi, 

Would like to integrate TWCManager with my energy monitoring in Home Assistant. Witch TWCManager fork should I use that is compatible with your component?

What kind of configuration is needed?

Thanks!

**Comment by jherby2k** [comment]
You can use the latest release from the ngartner branch which is the one in
active development. Just don't configure the home assistant integration
stuff in TWCManager's config and install my Addin instead. It just polls
the REST API to populate sensors.

If you want to have TWCManager actually pull energy production values FROM
HA you'll still want to configure that part. I'd recommend you have
TWCManager pull energy data right from your energy monitoring solution
though so that TWCManager keeps working if HA goes down.

**Comment by surfarn** [comment]
Thanks for the response, 

I am using a slimmelezer with esphome, so I guess there should be some possibilities to communicate directly to the TWCManager.
